---
- name: Close firewall
  hosts: all

  tasks:
    - name: Close http in the firewall
      firewalld:
        service: http
        permanent: true
        immediate: true
        state: disabled
