---
- name: Configure firewall
  hosts: all

  tasks:
    - name: Open http in the firewall
      firewalld:
        service: http
        permanent: true
        immediate: true
        state: enabled
