---
- name: Install Notepad++ 
  hosts: windows 
  become: yes
  become-user: Administrator
  become-method: runas

  tasks:
  - name: notepad 
    win_chocolatey:
      name: 
      - notepadplusplus
      - notepadplusplus.install
      state: present
